name: Check build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
